from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

from agent_persona.collectors.file_patterns import collect_file_signals
from agent_persona.collectors.shell_history import _clean_lines, collect_shell_history
from agent_persona.collectors.transcript import (
    collect_transcript,
    find_unprocessed_transcripts,
    mark_processed,
)

NOW = "2024-06-01T00:00:00+00:00"

# ── transcript helpers ────────────────────────────────────────────────────────


def _write_jsonl(path: Path, records: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        for record in records:
            fh.write(json.dumps(record) + "\n")


def _user_text_record(text: str) -> dict:
    return {"message": {"role": "user", "content": text}}


def _tool_use_record(tool: str, **kwargs: str) -> dict:
    block = {"type": "tool_use", "name": tool, "input": kwargs}
    return {"message": {"role": "assistant", "content": [block]}}


# ── transcript.py ─────────────────────────────────────────────────────────────


def test_collect_transcript_returns_user_messages_and_tool_signals(tmp_path: Path) -> None:
    """collect_transcript() extracts user text and file paths from a valid JSONL."""
    transcript = tmp_path / "session.jsonl"
    _write_jsonl(
        transcript,
        [
            _user_text_record("I prefer root-cause analysis"),
            _tool_use_record("Read", file_path="/src/main.py"),
        ],
    )
    state_store = tmp_path / "state"

    user_msgs, tool_signals = collect_transcript(transcript, state_store)

    assert "I prefer root-cause analysis" in user_msgs
    assert "/src/main.py" in tool_signals


def test_collect_transcript_skips_non_user_role(tmp_path: Path) -> None:
    """collect_transcript() does not add assistant messages to user_messages."""
    transcript = tmp_path / "session.jsonl"
    _write_jsonl(
        transcript,
        [
            {"message": {"role": "assistant", "content": "assistant reply"}},
            _user_text_record("user says hi"),
        ],
    )
    state_store = tmp_path / "state"

    user_msgs, _ = collect_transcript(transcript, state_store)

    assert "assistant reply" not in user_msgs
    assert "user says hi" in user_msgs


def test_collect_transcript_skips_lines_over_2mb(tmp_path: Path) -> None:
    """collect_transcript() silently skips lines larger than 2 MB."""
    transcript = tmp_path / "session.jsonl"
    big_line = ("x" * (2 * 1024 * 1024 + 1) + "\n").encode()
    normal_record = (json.dumps(_user_text_record("normal")) + "\n").encode()

    with transcript.open("wb") as fh:
        fh.write(big_line)
        fh.write(normal_record)

    state_store = tmp_path / "state"

    user_msgs, _ = collect_transcript(transcript, state_store)

    assert "normal" in user_msgs


def test_collect_transcript_skips_bad_json_lines(tmp_path: Path) -> None:
    """collect_transcript() silently ignores lines with invalid JSON."""
    transcript = tmp_path / "session.jsonl"
    with transcript.open("w", encoding="utf-8") as fh:
        fh.write("NOT JSON AT ALL\n")
        fh.write(json.dumps(_user_text_record("valid line")) + "\n")

    state_store = tmp_path / "state"

    user_msgs, _ = collect_transcript(transcript, state_store)

    assert "valid line" in user_msgs


def test_collect_transcript_skips_meta_records(tmp_path: Path) -> None:
    """User records flagged isMeta are system-injected and must be ignored."""
    transcript = tmp_path / "session.jsonl"
    meta = {"isMeta": True, "message": {"role": "user", "content": "Continue from where you left off."}}
    _write_jsonl(transcript, [meta, _user_text_record("real prompt here")])

    user_msgs, _ = collect_transcript(transcript, tmp_path / "state")

    assert "real prompt here" in user_msgs
    assert "Continue from where you left off." not in user_msgs


def test_collect_transcript_filters_injected_markers(tmp_path: Path) -> None:
    """Slash-command wrappers, command output, hook feedback, and reminders
    are never treated as user preferences."""
    transcript = tmp_path / "session.jsonl"
    injected = [
        "<command-name>/plan</command-name>\n<command-message>plan</command-message>",
        "<local-command-stdout>Enabled plan mode</local-command-stdout>",
        "<local-command-caveat>Caveat: The messages below were generated by the user</local-command-caveat>",
        "<system-reminder>always use tabs and never do X</system-reminder>",
        "Stop hook feedback:\n[Silent background task. always use Y, never do Z]",
        "[Request interrupted by user]",
    ]
    records = [_user_text_record(t) for t in injected]
    records.append(_user_text_record("I prefer concise answers"))
    _write_jsonl(transcript, records)

    user_msgs, _ = collect_transcript(transcript, tmp_path / "state")

    assert user_msgs == ["I prefer concise answers"]


def test_find_unprocessed_transcripts_excludes_processed(tmp_path: Path) -> None:
    """find_unprocessed_transcripts() omits session IDs already in state.json."""
    claude_dir = tmp_path / ".claude"
    projects_dir = claude_dir / "projects" / "proj1"
    projects_dir.mkdir(parents=True)

    processed_session = projects_dir / "abc123.jsonl"
    unprocessed_session = projects_dir / "def456.jsonl"
    processed_session.write_text("{}\n")
    unprocessed_session.write_text("{}\n")

    state_store = tmp_path / "state"
    state_store.mkdir()
    (state_store / "state.json").write_text(
        json.dumps({"processed_sessions": ["abc123"]}), encoding="utf-8"
    )

    result = find_unprocessed_transcripts(claude_dir=claude_dir, state_store=state_store)

    result_stems = [p.stem for p in result]
    assert "abc123" not in result_stems
    assert "def456" in result_stems


def test_mark_processed_adds_id_to_state_json(tmp_path: Path) -> None:
    """mark_processed() writes the session id into state.json."""
    state_store = tmp_path / "state"

    mark_processed("session-xyz", state_store)

    state = json.loads((state_store / "state.json").read_text())
    assert "session-xyz" in state["processed_sessions"]


def test_mark_processed_caps_at_500(tmp_path: Path) -> None:
    """mark_processed() keeps the processed_sessions list at most 500 entries."""
    state_store = tmp_path / "state"
    state_store.mkdir()
    existing_ids = [f"old-{i}" for i in range(500)]
    (state_store / "state.json").write_text(
        json.dumps({"processed_sessions": existing_ids}), encoding="utf-8"
    )

    mark_processed("new-session", state_store)

    state = json.loads((state_store / "state.json").read_text())
    assert len(state["processed_sessions"]) <= 500
    assert "new-session" in state["processed_sessions"]


# ── shell_history.py ──────────────────────────────────────────────────────────


def test_collect_shell_history_reads_commands(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """collect_shell_history() returns commands from a mock history file."""
    history_file = tmp_path / ".zsh_history"
    history_file.write_text("git status\npytest tests/\ndocker ps\n", encoding="utf-8")

    import agent_persona.collectors.shell_history as sh_mod

    monkeypatch.setattr(sh_mod, "_HISTORY_FILES", [history_file])

    result = collect_shell_history(limit=500)

    assert "git status" in result
    assert "pytest tests/" in result


def test_collect_shell_history_strips_zsh_timestamp_prefix() -> None:
    """_clean_lines() strips the ': 1234567:0;' zsh timestamp prefix."""
    lines = [
        ": 1617000000:0;git commit -m 'fix'",
        ": 1617000001:0;docker build .",
    ]

    result = _clean_lines(lines)

    assert all(not line.startswith(": ") for line in result)
    assert any("git commit" in line for line in result)
    assert any("docker build" in line for line in result)


def test_collect_shell_history_returns_empty_when_no_file(monkeypatch: pytest.MonkeyPatch) -> None:
    """collect_shell_history() returns [] when no history file exists."""
    import agent_persona.collectors.shell_history as sh_mod

    monkeypatch.setattr(sh_mod, "_HISTORY_FILES", [])

    result = collect_shell_history()

    assert result == []


# ── file_patterns.py ──────────────────────────────────────────────────────────


def _recent_ts() -> str:
    return (datetime.now(timezone.utc) - timedelta(days=1)).isoformat()


def _old_ts() -> str:
    return (datetime.now(timezone.utc) - timedelta(days=100)).isoformat()


def test_collect_file_signals_counts_extensions(tmp_path: Path) -> None:
    """collect_file_signals() returns correct extension counts from a JSONL log."""
    store = tmp_path / "store"
    log_dir = store / "history"
    log_dir.mkdir(parents=True)
    log_path = log_dir / "files_edited.jsonl"

    entries = [
        {"timestamp": _recent_ts(), "ext": ".py", "path": "/proj/main.py"},
        {"timestamp": _recent_ts(), "ext": ".py", "path": "/proj/utils.py"},
        {"timestamp": _recent_ts(), "ext": ".ts", "path": "/proj/app.ts"},
    ]
    log_path.write_text("\n".join(json.dumps(e) for e in entries), encoding="utf-8")

    signals = collect_file_signals(store)

    assert signals["extensions"].get("py", 0) == 2
    assert signals["extensions"].get("ts", 0) == 1


def test_collect_file_signals_skips_entries_older_than_90_days(tmp_path: Path) -> None:
    """collect_file_signals() ignores entries with timestamps older than 90 days."""
    store = tmp_path / "store"
    log_dir = store / "history"
    log_dir.mkdir(parents=True)
    log_path = log_dir / "files_edited.jsonl"

    entries = [
        {"timestamp": _old_ts(), "ext": ".rb", "path": "/old/file.rb"},
        {"timestamp": _recent_ts(), "ext": ".py", "path": "/new/file.py"},
    ]
    log_path.write_text("\n".join(json.dumps(e) for e in entries), encoding="utf-8")

    signals = collect_file_signals(store)

    assert signals["extensions"].get("rb", 0) == 0
    assert signals["extensions"].get("py", 0) == 1


def test_collect_file_signals_counts_test_files(tmp_path: Path) -> None:
    """collect_file_signals() counts paths containing 'test' in their file name."""
    store = tmp_path / "store"
    log_dir = store / "history"
    log_dir.mkdir(parents=True)
    log_path = log_dir / "files_edited.jsonl"

    entries = [
        {"timestamp": _recent_ts(), "ext": ".py", "path": "/proj/test_models.py"},
        {"timestamp": _recent_ts(), "ext": ".py", "path": "/proj/models.py"},
        {"timestamp": _recent_ts(), "ext": ".py", "path": "/proj/test_views.py"},
    ]
    log_path.write_text("\n".join(json.dumps(e) for e in entries), encoding="utf-8")

    signals = collect_file_signals(store)

    assert signals["test_file_count"] == 2
    assert signals["total_file_count"] == 3


# ── file_patterns.py additional coverage ─────────────────────────────────────


def test_collect_file_signals_returns_defaults_when_no_log(tmp_path: Path) -> None:
    """collect_file_signals() returns empty dicts when the log file is absent."""
    store = tmp_path / "store"
    store.mkdir()

    signals = collect_file_signals(store)

    assert signals["extensions"] == {}
    assert signals["total_file_count"] == 0
    assert signals["test_file_count"] == 0


def test_collect_file_signals_skips_bad_json_lines(tmp_path: Path) -> None:
    """collect_file_signals() silently ignores malformed JSON lines."""
    store = tmp_path / "store"
    log_dir = store / "history"
    log_dir.mkdir(parents=True)
    log_path = log_dir / "files_edited.jsonl"

    lines = [
        "NOT JSON AT ALL\n",
        json.dumps({"timestamp": _recent_ts(), "ext": ".go", "path": "/proj/main.go"}) + "\n",
    ]
    log_path.write_text("".join(lines), encoding="utf-8")

    signals = collect_file_signals(store)

    assert signals["extensions"].get("go", 0) == 1


def test_collect_file_signals_skips_entries_missing_timestamp(tmp_path: Path) -> None:
    """collect_file_signals() skips entries where 'timestamp' is unparseable."""
    store = tmp_path / "store"
    log_dir = store / "history"
    log_dir.mkdir(parents=True)
    log_path = log_dir / "files_edited.jsonl"

    entries = [
        {"timestamp": "NOT_A_DATE", "ext": ".rs", "path": "/proj/main.rs"},
        {"timestamp": _recent_ts(), "ext": ".py", "path": "/proj/app.py"},
    ]
    log_path.write_text("\n".join(json.dumps(e) for e in entries), encoding="utf-8")

    signals = collect_file_signals(store)

    assert signals["extensions"].get("rs", 0) == 0
    assert signals["extensions"].get("py", 0) == 1


def test_collect_file_signals_detects_tabs_indent(tmp_path: Path) -> None:
    """collect_file_signals() detects tab indentation from real file content."""
    store = tmp_path / "store"
    log_dir = store / "history"
    log_dir.mkdir(parents=True)
    log_path = log_dir / "files_edited.jsonl"

    # Create a real file with tab-indented content
    tab_file = tmp_path / "tabbed.go"
    tab_file.write_text("package main\n\nfunc main() {\n\tprintln(\"hi\")\n}\n", encoding="utf-8")

    entry = {"timestamp": _recent_ts(), "ext": ".go", "path": str(tab_file)}
    log_path.write_text(json.dumps(entry) + "\n", encoding="utf-8")

    signals = collect_file_signals(store)

    assert signals["indent"] == "tabs"


def test_collect_file_signals_detects_spaces_indent(tmp_path: Path) -> None:
    """collect_file_signals() detects space indentation from real file content."""
    store = tmp_path / "store"
    log_dir = store / "history"
    log_dir.mkdir(parents=True)
    log_path = log_dir / "files_edited.jsonl"

    space_file = tmp_path / "spaced.py"
    space_file.write_text("def foo():\n    pass\n    return 1\n", encoding="utf-8")

    entry = {"timestamp": _recent_ts(), "ext": ".py", "path": str(space_file)}
    log_path.write_text(json.dumps(entry) + "\n", encoding="utf-8")

    signals = collect_file_signals(store)

    assert signals["indent"] == "spaces"
    assert signals["indent_size"] == 4


def test_collect_file_signals_handles_nonexistent_file_in_log(tmp_path: Path) -> None:
    """collect_file_signals() tolerates paths in log that no longer exist on disk."""
    store = tmp_path / "store"
    log_dir = store / "history"
    log_dir.mkdir(parents=True)
    log_path = log_dir / "files_edited.jsonl"

    entry = {"timestamp": _recent_ts(), "ext": ".py", "path": "/nonexistent/path/file.py"}
    log_path.write_text(json.dumps(entry) + "\n", encoding="utf-8")

    # Should not raise even if the file on disk does not exist
    signals = collect_file_signals(store)
    assert signals["extensions"].get("py", 0) == 1


def test_collect_file_signals_counts_spec_files(tmp_path: Path) -> None:
    """collect_file_signals() counts 'spec' files as test files."""
    store = tmp_path / "store"
    log_dir = store / "history"
    log_dir.mkdir(parents=True)
    log_path = log_dir / "files_edited.jsonl"

    entries = [
        {"timestamp": _recent_ts(), "ext": ".rb", "path": "/proj/user_spec.rb"},
        {"timestamp": _recent_ts(), "ext": ".rb", "path": "/proj/user.rb"},
    ]
    log_path.write_text("\n".join(json.dumps(e) for e in entries), encoding="utf-8")

    signals = collect_file_signals(store)

    assert signals["test_file_count"] == 1


# ── transcript.py additional coverage ────────────────────────────────────────


def test_collect_transcript_handles_user_content_as_list(tmp_path: Path) -> None:
    """collect_transcript() extracts text from list-typed user content blocks."""
    transcript = tmp_path / "session.jsonl"
    record = {
        "message": {
            "role": "user",
            "content": [
                {"type": "text", "text": "Please use snake_case"},
                {"type": "image", "data": "..."},  # non-text block, should be skipped
            ],
        }
    }
    transcript.write_text(json.dumps(record) + "\n", encoding="utf-8")
    state_store = tmp_path / "state"

    user_msgs, _ = collect_transcript(transcript, state_store)

    assert "Please use snake_case" in user_msgs


def test_collect_transcript_extracts_bash_tool_signals(tmp_path: Path) -> None:
    """collect_transcript() adds Bash commands to tool_signals."""
    transcript = tmp_path / "session.jsonl"
    record = {
        "message": {
            "role": "assistant",
            "content": [
                {"type": "tool_use", "name": "Bash", "input": {"command": "pytest tests/ -v"}}
            ],
        }
    }
    transcript.write_text(json.dumps(record) + "\n", encoding="utf-8")
    state_store = tmp_path / "state"

    _, tool_signals = collect_transcript(transcript, state_store)

    assert "pytest tests/ -v" in tool_signals


def test_collect_transcript_extracts_write_tool_signals(tmp_path: Path) -> None:
    """collect_transcript() adds Write tool file paths to tool_signals."""
    transcript = tmp_path / "session.jsonl"
    record = {
        "message": {
            "role": "assistant",
            "content": [
                {"type": "tool_use", "name": "Write", "input": {"file_path": "/src/new_file.py"}}
            ],
        }
    }
    transcript.write_text(json.dumps(record) + "\n", encoding="utf-8")
    state_store = tmp_path / "state"

    _, tool_signals = collect_transcript(transcript, state_store)

    assert "/src/new_file.py" in tool_signals


def test_collect_transcript_ignores_non_dict_records(tmp_path: Path) -> None:
    """collect_transcript() silently skips non-dict JSON values."""
    transcript = tmp_path / "session.jsonl"
    with transcript.open("w") as fh:
        fh.write(json.dumps(["not", "a", "dict"]) + "\n")
        fh.write(json.dumps(_user_text_record("real message")) + "\n")
    state_store = tmp_path / "state"

    user_msgs, _ = collect_transcript(transcript, state_store)

    assert "real message" in user_msgs


def test_find_unprocessed_transcripts_excludes_subagents(tmp_path: Path) -> None:
    """find_unprocessed_transcripts() skips paths containing '/subagents/'."""
    claude_dir = tmp_path / ".claude"
    projects_dir = claude_dir / "projects" / "proj1"
    subagents_dir = claude_dir / "projects" / "proj1" / "subagents"
    projects_dir.mkdir(parents=True)
    subagents_dir.mkdir(parents=True)

    normal_session = projects_dir / "normal_session.jsonl"
    subagent_session = subagents_dir / "subagent_session.jsonl"
    normal_session.write_text("{}\n")
    subagent_session.write_text("{}\n")

    state_store = tmp_path / "state"
    state_store.mkdir()
    (state_store / "state.json").write_text(
        json.dumps({"processed_sessions": []}), encoding="utf-8"
    )

    result = find_unprocessed_transcripts(claude_dir=claude_dir, state_store=state_store)

    result_stems = [p.stem for p in result]
    assert "normal_session" in result_stems
    assert "subagent_session" not in result_stems


def test_find_unprocessed_transcripts_requires_state_store(tmp_path: Path) -> None:
    """find_unprocessed_transcripts() raises ValueError when state_store is None."""
    with pytest.raises(ValueError, match="state_store is required"):
        find_unprocessed_transcripts(claude_dir=tmp_path, state_store=None)
